////////////////////////////////////////////////////////////////////////////////
//Declare type converters from DBTYPE_UI4.
//                                                     Roman Piminov, 14.03.2008
////////////////////////////////////////////////////////////////////////////////

DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,error)

DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,i1)
DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,i2)
DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,i4)
DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,i8)

DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,ui1)
DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,ui2)
DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,ui4)
DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,ui8)

DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,r4)
DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,r8)

DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,cy)
DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,decimal)
DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,numeric)

DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,str)
DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,wstr)
DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,bstr)

DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,bool)

DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,bytes)

DECLARE_OLEDB_TYPE_CONVERTER_V3(ui4,variant)

DECLARE_OLEDB_TYPE_CONVERTER_V3__TO_IUNKNOWN(ui4)

DECLARE_OLEDB_TYPE_CONVERTER_TO_ARRAY_V2(ui4,array_ui1)

////////////////////////////////////////////////////////////////////////////////
