////////////////////////////////////////////////////////////////////////////////
//DBVARIANT Comparator.
//                                                Kovalenko Dmitry. 07.10.2017.

////////////////////////////////////////////////////////////////////////////////

#include <ole_lib/oledb/variant/comparator2/impl/simple/guid/oledb_variant_cmp2__guid__guid.cxx>

////////////////////////////////////////////////////////////////////////////////

extern const TDBVariantComparator2_Descr2 g_DBVariantComparator2_Descrs2__GUID__Simple[]=
{
 /* 0*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),                  //DBTYPE_EMPTY
 /* 1*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NULL2(GUID),             //DBTYPE_NULL
 /* 2*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),                  //DBTYPE_I2
 /* 3*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),                  //DBTYPE_I4
 /* 4*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),                  //DBTYPE_R4
 /* 5*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),                  //DBTYPE_R8
 /* 6*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),                  //DBTYPE_CY
 /* 7*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),                  //DBTYPE_DATE
 /* 8*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),                  //DBTYPE_BSTR
 /* 9*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*10*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*11*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),                  //DBTYPE_BOOL
 /*12*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__VARIANT2(GUID),
 /*13*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*14*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*15*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*16*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),                  //DBTYPE_I1
 /*17*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),                  //DBTYPE_UI1
 /*18*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),                  //DBTYPE_UI2
 /*19*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),                  //DBTYPE_UI4
 /*20*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),                  //DBTYPE_I8
 /*21*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),                  //DBTYPE_UI8
 /*22*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*23*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*24*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*25*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*26*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*27*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*28*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*29*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*30*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*31*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*32*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*33*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*34*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*35*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*36*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*37*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*38*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*39*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*40*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*41*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*42*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*43*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*44*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*45*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*46*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*47*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*48*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*49*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*50*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*51*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*52*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*53*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*54*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*55*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*56*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*57*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*58*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*59*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*60*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*61*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*62*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*63*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*64*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*65*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*66*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*67*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*68*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*69*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*70*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*71*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__NONE(),
 /*72*/ OLEDB_VARIANT_COMPARATOR2_DESCR2__SIMPLE(GUID,GUID),
};//g_DBVariantComparator2_Descrs2__GUID__Simple

////////////////////////////////////////////////////////////////////////////////

extern const TDBVariantComparator2_Descr1
 g_DBVariantComparator2_Descr1__GUID__Simple
  (_DIM_(g_DBVariantComparator2_Descrs2__GUID__Simple),
   g_DBVariantComparator2_Descrs2__GUID__Simple
   _DEBUG_ARG(oledb_typeid__GUID)
   _DEBUG_ARG(0));

////////////////////////////////////////////////////////////////////////////////
