////////////////////////////////////////////////////////////////////////////////
//Declare type converters from DBTYPE_R8.
//                                                     Roman Piminov, 14.03.2008
////////////////////////////////////////////////////////////////////////////////

DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,i1)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,i2)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,i4)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,i8)

DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,ui1)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,ui2)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,ui4)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,ui8)

DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,r4)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,r8)

DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,cy)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,decimal)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,numeric)

DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,date)

DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,str)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,wstr)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,bstr)

DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,bool)

DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,bytes)

DECLARE_OLEDB_TYPE_CONVERTER_V3(r8,variant)

DECLARE_OLEDB_TYPE_CONVERTER_V3__TO_IUNKNOWN(r8)

DECLARE_OLEDB_TYPE_CONVERTER_TO_ARRAY_V2(r8,array_ui1)

////////////////////////////////////////////////////////////////////////////////
