////////////////////////////////////////////////////////////////////////////////
//Declare type converters from DBTYPE_I4.
//                                                     Roman Piminov, 14.03.2008
////////////////////////////////////////////////////////////////////////////////

DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,error)

DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,i1)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,i2)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,i4)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,i8)

DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,ui1)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,ui2)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,ui4)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,ui8)

DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,r4)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,r8)

DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,cy)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,decimal)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,numeric)

DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,str)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,wstr)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,bstr)

DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,bool)

DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,bytes)

DECLARE_OLEDB_TYPE_CONVERTER_V3(i4,variant)

DECLARE_OLEDB_TYPE_CONVERTER_V3__TO_IUNKNOWN(i4)

DECLARE_OLEDB_TYPE_CONVERTER_TO_ARRAY_V2(i4,array_ui1)

////////////////////////////////////////////////////////////////////////////////
