////////////////////////////////////////////////////////////////////////////////
//Declare type converters from DBTYPE_R4.
//                                                     Roman Piminov, 14.03.2008
////////////////////////////////////////////////////////////////////////////////

DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,i1)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,i2)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,i4)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,i8)

DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,ui1)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,ui2)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,ui4)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,ui8)

DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,r4)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,r8)

DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,cy)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,decimal)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,numeric)

DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,str)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,wstr)
DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,bstr)

DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,bool)

DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,bytes)

DECLARE_OLEDB_TYPE_CONVERTER_V3(r4,variant)

DECLARE_OLEDB_TYPE_CONVERTER_V3__TO_IUNKNOWN(r4)

DECLARE_OLEDB_TYPE_CONVERTER_TO_ARRAY_V2(r4,array_ui1)

////////////////////////////////////////////////////////////////////////////////
