////////////////////////////////////////////////////////////////////////////////
//Declare type converters from DBTYPE_I2.
//                                                     Roman Piminov, 14.03.2008
////////////////////////////////////////////////////////////////////////////////

DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,i1)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,i2)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,i4)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,i8)

DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,ui1)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,ui2)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,ui4)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,ui8)

DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,r4)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,r8)

DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,cy)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,decimal)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,numeric)

DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,str)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,wstr)
DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,bstr)

DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,bool)

DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,bytes)

DECLARE_OLEDB_TYPE_CONVERTER_V3(i2,variant)

DECLARE_OLEDB_TYPE_CONVERTER_V3__TO_IUNKNOWN(i2)

DECLARE_OLEDB_TYPE_CONVERTER_TO_ARRAY_V2(i2,array_ui1)

////////////////////////////////////////////////////////////////////////////////
